# Generated by Django 4.2.13 on 2024-07-09 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_project_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='about',
        ),
    ]
