# Generated by Django 4.2.13 on 2024-07-09 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_rename_project_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='Project',
        ),
    ]
