# Generated by Django 4.2.13 on 2024-07-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_project_options_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(default='Unknown Role', max_length=100),
        ),
    ]
